config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'livros/index'

  get 'livros/listaAdmin'
  get 'livros/listaNormalUser'
  post 'livros/edit' => 'livros#edit'

  post 'livros/update' => 'livros#update'

  delete 'livros/destroy' => 'livros#destroy'

  post 'livros' => 'livros#create'

  get 'authors/index'

  post 'authors' => 'authors#create'

  post 'instituicaos' => 'instituicaos#create'

  get 'instituicaos/index'

  get 'editoras/index'

  get 'home/index'

  get 'minhabiblioteca/index'

  get 'cadastro/index'

  get 'contato/index'

  get 'cadpesinst/index'

  get 'locacaos/index'

  post 'locacaos' => 'locacaos#create'

  get 'pessoas/index'

  post 'pessoas' => 'pessoas#create'

  post 'editoras' => 'editoras#create'

  resources :pessoas
  resources :livros
  resources :editoras
  resources :authors
  resources :locacaos
  resources :home, :only => [:index]
  resources :contato, :only => [:index]
  resources :cadastro, :only => [:index]
  resources :cadpesinst, :only => [:index]
  resources :minhabiblioteca, :only => [:index]
  resources :instituicaos

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :livros
end

app/models/editora.rb
class Editora < ActiveRecord::Base
  has_many :livros
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  belongs_to :livro
end

app/models/instituicao.rb
class Instituicao < ActiveRecord::Base
  has_many :pessoas
end

app/models/livro.rb
class Livro < ActiveRecord::Base
  belongs_to :author
  belongs_to :editora
  belongs_to :locacao
end

app/models/locacao.rb
class Locacao < ActiveRecord::Base
  belongs_to :livro
  belongs_to :pessoa
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  belongs_to :instituicao
  belongs_to :locacao
  belongs_to :reserva
  belongs_to :user
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :pessoas
  belongs_to :livros
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
belongs_to :pessoa
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: AuthorsDatatable.new(view_context) }
    end
  end
  def show
    @autors = Author.find(params[:id])

  end
  def new
    @autors = Author.new
    authorize @autors
  end
  def create
    @autors = Author.new(author_params)
    authorize @autors
    respond_to do |format|
      if @autors.save
        #format.html { redirect_to @editoras, notice: 'Post was successfully created.' }
        data = {:message => "Cadastro realizado com sucesso!"}
        format.json{render :json => data, :status => :ok}
      else
        #format.html { render :new }
        format.json { render :json => "erro ao cadastrar!" }
      end
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_authors
    @autors = Author.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.permit(:nome_author)
  end
end

app/controllers/cadpesinst_controller.rb
class CadpesinstController < ApplicationController
def index

end

end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:edit, :show, :update, :destroy]

  def index

  end

  def listaAdmin
    respond_to do |format|
      format.html
      format.json { render json: LivrosDatatableAdmin.new(view_context) }
    end
  end

  def listaNormalUser
    respond_to do |format|
      format.html
      format.json { render json: LivrosDatatableNormalUser.new(view_context) }
    end

  end

  def new
    @livros = Livro.new
    authorize @livros
  end

  def create
    @livros = Livro.new(livro_params)
    respond_to do |format|
      if @livros.save
        #format.html { redirect_to @pessoas, notice: 'Post was successfully created.' }
        data = {:message => "Cadastro realizado com sucesso!"}
        format.json { render :json => data, :status => :ok }
      else
        #format.html { render :new }
        format.json { render :json => "erro ao cadastrar!" }
      end
    end
  end

  def edit
    respond_to do |format|
      data = {:titulo => @livros.titulo, :ano => @livros.ano, :estante => @livros.estante, :prateleira => @livros.prateleira}
      format.json { render :json => data, :status => :ok }
    end
  end

  def update
    respond_to do |format|
      if @livros.update_attributes(livro_params)
        data = {:message => "Alteração realizada com sucesso!"}
        format.json { render :json => data, :status => :ok }
      else
        format.json { render :json => "erro ao atualizar!" }
      end
    end
  end

  def destroy
    respond_to do |format|
      @livros.destroy
      data = {:message => "Exclusão realizada com sucesso!"}
      format.json { render :json => data, :status => :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_livro
    @livros = Livro.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def livro_params
    params.permit(:titulo, :ano, :estante, :prateleira, :editora_id, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/editoras_helper.rb
module EditorasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instituicaos_helper.rb
module InstituicaosHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/cadpesinst/index.html.erb
<div id="modalinstituicao" class="modal fade" data-width="760" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Instituições</h4>
  </div>
  <table id="tableinstituicao" cellspacing="0" width="100%" class="table table-striped table-bordered display responsive no-wrap" data-source="<%= instituicaos_url(format: "json") %>">
    <thead>
    <tr>
      <th>ID</th>
      <th>Instituição</th>
    </tr>
    </thead>
    <tbody>

    </tbody>
  </table>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-success">OK</button>
  </div>
</div>
<div class="section alert-warning">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <form class="form-horizontal">
          <fieldset>
            <!-- Form Name -->
            <legend>Cadastro Pessoa</legend>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="nameinput">Nome</label>
              <div class="col-md-8">
                <input id="inputnome" name="nameinput" type="text" placeholder="Nome" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="matinput">Matricula</label>
              <div class="col-md-4">
                <input id="inputmatricula" name="matinput" type="text" placeholder="Matricula" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="cpfinput">CPF</label>
              <div class="col-md-4">
                <input id="inputCPF" name="cpfinput" type="text" placeholder="CPF" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Select Basic -->
            <div class="form-group">
              <label class="col-md-4 control-label" for="status">Tipo</label>
              <div class="col-md-4">
                <select id="status" name="status" class="form-control">
                  <option value="1">Administrador</option>
                  <option value="2">Usuário</option>
                </select>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="logininput">Login</label>
              <div class="col-md-4">
                <input id="inputlogin" name="logininput" type="text" placeholder="Login" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="senhainput">Senha</label>
              <div class="col-md-4">
                <input id="passwordinput" name="senhainput" type="text" placeholder="Senha" class="form-control input-md" required="">
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="senha2input">Repetir Senha</label>
              <div class="col-md-4">
                <input id="password2input" name="senha2input" type="text" placeholder="Senha" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="instituicaoinput">Instituição</label>

              <div class="col-md-4">
                <input id="instituicaoinput" name="instituicaoinput" type="text" placeholder="Instituição" class="form-control input-md" disabled required="">
                <span class="help-block">Ajuda</span>
              </div>
              <div class="col-md-4">
                <button id="addinstituicao" name="addinstituicao" class="btn btn-primary glyphicon glyphicon-plus"></button>
              </div>
            </div>
            <!-- Button (Double) -->
            <div class="form-group">
              <label class="col-md-4 control-label" for="button1id"></label>
              <div class="col-md-8">
                <button id="buttonCadastrar" name="button1id" class="btn btn-success">Enviar Dados</button>
                <button id="button2idpessoa" name="button2id" class="btn btn-danger">Apagar Tudo</button>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
      <div class="col-md-6">
        <form class="form-horizontal">
          <fieldset>
            <!-- Form Name -->
            <legend>Cadastro Instituição</legend>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="nameinput">Nome</label>
              <div class="col-md-4">
                <input id="nameinput" name="nameinput" type="text" placeholder="Nome" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="endinput">Endereço</label>
              <div class="col-md-8">
                <input id="endinput" name="endinput" type="text" placeholder="Endereço" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="respinput">Responsável</label>
              <div class="col-md-4">
                <input id="respinput" name="respinput" type="text" placeholder="Responsável" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Button (Double) -->
            <div class="form-group">
              <label class="col-md-4 control-label" for="button1id"></label>
              <div class="col-md-8">
                <button id="button1idinstituicao" name="button1id" class="btn btn-success">Enviar Dados</button>
                <button id="button2idinstituicao" name="button2id" class="btn btn-danger">Apagar Tudo</button>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>