config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'livros/index'

  get 'livros/listaAdmin'
  get 'livros/listaNormalUser'
  post 'livros/edit' => 'livros#edit'

  post 'livros/update' => 'livros#update'

  delete 'livros/destroy' => 'livros#destroy'

  post 'livros' => 'livros#create'

  get 'authors/index'

  post 'authors' => 'authors#create'

  post 'instituicaos' => 'instituicaos#create'

  get 'instituicaos/index'

  get 'editoras/index'

  get 'home/index'

  get 'minhabiblioteca/index'

  get 'cadastro/index'

  get 'contato/index'

  get 'cadpesinst/index'

  get 'locacaos/index'

  post 'locacaos' => 'locacaos#create'

  get 'pessoas/index'

  post 'pessoas' => 'pessoas#create'

  post 'editoras' => 'editoras#create'

  resources :pessoas
  resources :livros
  resources :editoras
  resources :authors
  resources :locacaos
  resources :home, :only => [:index]
  resources :contato, :only => [:index]
  resources :cadastro, :only => [:index]
  resources :cadpesinst, :only => [:index]
  resources :minhabiblioteca, :only => [:index]
  resources :instituicaos

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :livros
end

app/models/editora.rb
class Editora < ActiveRecord::Base
  has_many :livros
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  belongs_to :livro
end

app/models/instituicao.rb
class Instituicao < ActiveRecord::Base
  has_many :pessoas
end

app/models/livro.rb
class Livro < ActiveRecord::Base
  belongs_to :author
  belongs_to :editora
  belongs_to :locacao
end

app/models/locacao.rb
class Locacao < ActiveRecord::Base
  belongs_to :livro
  belongs_to :pessoa
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  belongs_to :instituicao
  belongs_to :locacao
  belongs_to :reserva
  belongs_to :user
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :pessoas
  belongs_to :livros
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
belongs_to :pessoa
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: AuthorsDatatable.new(view_context) }
    end
  end
  def show
    @autors = Author.find(params[:id])

  end
  def new
    @autors = Author.new
    authorize @autors
  end
  def create
    @autors = Author.new(author_params)
    authorize @autors
    respond_to do |format|
      if @autors.save
        #format.html { redirect_to @editoras, notice: 'Post was successfully created.' }
        data = {:message => "Cadastro realizado com sucesso!"}
        format.json{render :json => data, :status => :ok}
      else
        #format.html { render :new }
        format.json { render :json => "erro ao cadastrar!" }
      end
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_authors
    @autors = Author.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.permit(:nome_author)
  end
end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:edit, :show, :update, :destroy]

  def index

  end

  def listaAdmin
    respond_to do |format|
      format.html
      format.json { render json: LivrosDatatableAdmin.new(view_context) }
    end
  end

  def listaNormalUser
    respond_to do |format|
      format.html
      format.json { render json: LivrosDatatableNormalUser.new(view_context) }
    end

  end

  def new
    @livros = Livro.new
    authorize @livros
  end

  def create
    @livros = Livro.new(livro_params)
    respond_to do |format|
      if @livros.save
        #format.html { redirect_to @pessoas, notice: 'Post was successfully created.' }
        data = {:message => "Cadastro realizado com sucesso!"}
        format.json { render :json => data, :status => :ok }
      else
        #format.html { render :new }
        format.json { render :json => "erro ao cadastrar!" }
      end
    end
  end

  def edit
    respond_to do |format|
      data = {:titulo => @livros.titulo, :ano => @livros.ano, :estante => @livros.estante, :prateleira => @livros.prateleira}
      format.json { render :json => data, :status => :ok }
    end
  end

  def update
    respond_to do |format|
      if @livros.update_attributes(livro_params)
        data = {:message => "Alteração realizada com sucesso!"}
        format.json { render :json => data, :status => :ok }
      else
        format.json { render :json => "erro ao atualizar!" }
      end
    end
  end

  def destroy
    respond_to do |format|
      @livros.destroy
      data = {:message => "Exclusão realizada com sucesso!"}
      format.json { render :json => data, :status => :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_livro
    @livros = Livro.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def livro_params
    params.permit(:titulo, :ano, :estante, :prateleira, :editora_id, :author_id)
  end
end

app/controllers/minhabiblioteca_controller.rb
class MinhabibliotecaController < ApplicationController
  before_action :authenticate_user!
  def index
    @livros = Livro.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/editoras_helper.rb
module EditorasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instituicaos_helper.rb
module InstituicaosHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/minhabiblioteca/index.html.erb
<div id="modaleditlivro" class="modal fade" data-width="800" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Editar Livro</h4>
  </div>
  <%= render "livros/form_livro" %>
  <div class="container">
    <div class="row">
      <!-- Button (Double) -->
      <div class="form-group">
        <label class="col-md-4 control-label" for="button1id"></label>

        <div class="col-md-8">
          <button id="button1updatelivro" name="button1id" class="btn btn-success">Atualizar Dados</button>
          <button id="button2idlivro" name="button2id" class="btn btn-danger">Apagar Tudo</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-success">OK</button>
  </div>
</div>
<div id="modalpessoalivro" class="modal fade" data-width="800" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Emprestar livro</h4>
  </div>
  <table id="tablepessoaslivro" cellspacing="0" width="100%" class="table table-striped table-bordered display responsive no-wrap" data-source="<%= pessoas_url(format: "json") %>">
    <thead>
    <tr>
      <th>ID</th>
      <th>Matricula</th>
      <th>CPF</th>
      <th>Nome</th>
    </tr>
    </thead>
    <tbody>

    </tbody>
  </table>
  <div class="modal-footer">
    <button type="button" id="buttonalocapeslivro" data-dismiss="modal" class="btn btn-success">OK</button>
  </div>
</div>
<div class="container">
  <div class="row">
    <form class="form-horizontal">
      <fieldset>
        <div class="col-md-12">
          <% if policy(@livros).index? %>
              <table id="livros" cellspacing="0" width="100%" class="table table-striped table-bordered display responsive no-wrap" data-source="<%= livros_listaAdmin_url(format: "json") %>">
          <% else %>
              <table id="livros" cellspacing="0" width="100%" class="table table-striped table-bordered display responsive no-wrap" data-source="<%= livros_listaNormalUser_url(format: "json") %>">
          <% end %>
          <thead>
          <tr>
            <th>ID</th>
            <th>Titulo</th>
            <th>Ano</th>
            <th>Prateleira</th>
            <th>Estante</th>
            <th>Autor</th>
            <th>Editora</th>
            <th>Opção</th>
          </tr>
          </thead>
          <tbody>

          </tbody>
          </table>
        </div>
      </fieldset>
    </form>
  </div>
</div>