config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'livros/index'

  get 'livros/listaAdmin'
  get 'livros/listaNormalUser'
  post 'livros/edit' => 'livros#edit'

  post 'livros/update' => 'livros#update'

  delete 'livros/destroy' => 'livros#destroy'

  post 'livros' => 'livros#create'

  get 'authors/index'

  post 'authors' => 'authors#create'

  post 'instituicaos' => 'instituicaos#create'

  get 'instituicaos/index'

  get 'editoras/index'

  get 'home/index'

  get 'minhabiblioteca/index'

  get 'cadastro/index'

  get 'contato/index'

  get 'cadpesinst/index'

  get 'locacaos/index'

  post 'locacaos' => 'locacaos#create'

  get 'pessoas/index'

  post 'pessoas' => 'pessoas#create'

  post 'editoras' => 'editoras#create'

  resources :pessoas
  resources :livros
  resources :editoras
  resources :authors
  resources :locacaos
  resources :home, :only => [:index]
  resources :contato, :only => [:index]
  resources :cadastro, :only => [:index]
  resources :cadpesinst, :only => [:index]
  resources :minhabiblioteca, :only => [:index]
  resources :instituicaos

end

app/models/livro.rb
class Livro < ActiveRecord::Base
  belongs_to :author
  belongs_to :editora
  belongs_to :locacao
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:edit, :show, :update, :destroy]

  def index

  end

  def listaAdmin
    respond_to do |format|
      format.html
      format.json { render json: LivrosDatatableAdmin.new(view_context) }
    end
  end

  def listaNormalUser
    respond_to do |format|
      format.html
      format.json { render json: LivrosDatatableNormalUser.new(view_context) }
    end

  end

  def new
    @livros = Livro.new
    authorize @livros
  end

  def create
    @livros = Livro.new(livro_params)
    respond_to do |format|
      if @livros.save
        #format.html { redirect_to @pessoas, notice: 'Post was successfully created.' }
        data = {:message => "Cadastro realizado com sucesso!"}
        format.json { render :json => data, :status => :ok }
      else
        #format.html { render :new }
        format.json { render :json => "erro ao cadastrar!" }
      end
    end
  end

  def edit
    respond_to do |format|
      data = {:titulo => @livros.titulo, :ano => @livros.ano, :estante => @livros.estante, :prateleira => @livros.prateleira}
      format.json { render :json => data, :status => :ok }
    end
  end

  def update
    respond_to do |format|
      if @livros.update_attributes(livro_params)
        data = {:message => "Alteração realizada com sucesso!"}
        format.json { render :json => data, :status => :ok }
      else
        format.json { render :json => "erro ao atualizar!" }
      end
    end
  end

  def destroy
    respond_to do |format|
      @livros.destroy
      data = {:message => "Exclusão realizada com sucesso!"}
      format.json { render :json => data, :status => :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_livro
    @livros = Livro.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def livro_params
    params.permit(:titulo, :ano, :estante, :prateleira, :editora_id, :author_id)
  end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/livros/_form_livro.html.erb
<div id="modaleditora" class="modal fade" data-width="760" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Editoras</h4>
  </div>
  <div class="form-group">
    <fieldset>
      <div class="form-group">
        <label class="col-md-4 control-label" for="salvaeditorainput">Editora</label>

        <div class="col-md-4">
          <input id="salvaeditorainput" name="salvaeditorainput" type="text" placeholder="Editora" class="form-control input-md">
        </div>
        <div class="col-md-4">
          <button id="salvaeditora" name="salvaeditora" class="btn btn-primary glyphicon glyphicon-save-file"></button>
        </div>
        </br>
      </div>
      </br>
    </fieldset>
  </div>
  <table id="tableeditoras" cellspacing="0" width="100%" class="table table-striped table-bordered display responsive no-wrap" data-source="<%= editoras_url(format: "json") %>">
    <thead>
    <tr>
      <th>ID</th>
      <th>Editora</th>
    </tr>
    </thead>
    <tbody>

    </tbody>
  </table>

  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-success">OK</button>
  </div>
</div>

<div id="modalauthor" class="modal fade" data-width="760" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Autores</h4>
  </div>
  <div class="form-group">
    <fieldset>
      <div class="form-group">
        <label class="col-md-4 control-label" for="salvaauthorinput">Autor</label>

        <div class="col-md-4">
          <input id="salvaauthorinput" name="salvaauthorinput" type="text" placeholder="Autor" class="form-control input-md">
        </div>
        <div class="col-md-4">
          <button id="salvaauthor" name="salvaauthor" class="btn btn-primary glyphicon glyphicon-save-file"></button>
        </div>
        </br>
      </div>
      </br>
    </fieldset>
  </div>
  <table id="tableauthors" cellspacing="0" width="100%" class="table table-striped table-bordered display responsive no-wrap" data-source="<%= authors_url(format: "json") %>">
    <thead>
    <tr>
      <th>ID</th>
      <th>Editora</th>
    </tr>
    </thead>
    <tbody>

    </tbody>
  </table>

  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-success">OK</button>
  </div>
</div>
<div class="section alert-warning">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <form class="form-horizontal">
          <fieldset>
            <!-- Form Name -->
            <legend>Livro</legend>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="tituloinput">Titulo</label>

              <div class="col-md-4">
                <input id="tituloinput" name="tituloinput" type="text" placeholder="Titulo" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="anoinput">Ano</label>

              <div class="col-md-4">
                <input id="anoinput" name="anoinput" type="text" placeholder="Ano" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="editorainput">Editora</label>

              <div class="col-md-4">
                <input id="editorainput" name="editorainput" type="text" placeholder="Editora" class="form-control input-md" disabled required="">
                <span class="help-block">Ajuda</span>
              </div>
              <div class="col-md-4">
                <button id="addeditora" name="addeditora" class="btn btn-primary glyphicon glyphicon-plus"></button>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="autorinput">Autor</label>

              <div class="col-md-4">
                <input id="autorinput" name="autorinput" type="text" placeholder="Autor" class="form-control input-md" disabled required="">
                <span class="help-block">Ajuda</span>
              </div>
              <div class="col-md-4">
                <button id="addautor" name="addeditora" class="btn btn-primary glyphicon glyphicon-plus"></button>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="estanteinput">Estante</label>

              <div class="col-md-4">
                <input id="estanteinput" name="estanteinput" type="text" placeholder="Estante" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="prateleirainput">Prateleira</label>

              <div class="col-md-4">
                <input id="prateleirainput" name="prateleirainput" type="text" placeholder="Prateleira" class="form-control input-md" required="">
                <span class="help-block">Ajuda</span>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/livros/index.html.erb
<h1>Livros#index</h1>
<p>Find me in app/views/livros/index.html.erb</p>

app/views/livros/new.html.erb
<%= render "form_livro" %>
<div class="container">
  <div class="row">
    <!-- Button (Double) -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="button1id"></label>

      <div class="col-md-8">
        <button id="button1idlivro" name="button1id" class="btn btn-success">Enviar Dados</button>
        <button id="button2idlivro" name="button2id" class="btn btn-danger">Apagar Tudo</button>
      </div>
    </div>
  </div>
</div>